
SELECT SD.STUDENT_ID,SD.STUDENT_NAME,SD.STUDENT_AGE,CI.CITY_NAME FROM STUDENT_DETAILS SD INNER JOIN CITY CI ON SD.STUDENT_CITY_ID=CI.CID WHERE CITY_NAME IN("Pune","Mumbai");

//Important For Grouping(GROUP_CONCAT Only for MYSQL Deliminator (,) and ORDER BY is Optional)
SELECT
    CI.CITY_NAME,
    GROUP_CONCAT(SD.STUDENT_NAME) AS STUDENTS
FROM STUDENT_DETAILS SD
JOIN CITY CI
    ON SD.STUDENT_CITY_ID = CI.CID
GROUP BY CI.CITY_NAME;


//Same Query for Oracle(LISTAGG with Deliminator (,) and ORDER BY is mandatory)

SELECT
    CI.CITY_NAME,
    LISTAGG(SD.STUDENT_NAME, ',')
        WITHIN GROUP (ORDER BY SD.STUDENT_NAME) AS STUDENTS
FROM STUDENT_DETAILS SD
JOIN CITY CI ON SD.STUDENT_CITY_ID = CI.CID
GROUP BY CI.CITY_NAME;